services:
  nginx:
    image: chimera-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"
    depends_on:
      - webapp
  cliapp:
    image: chimera-cliapp
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  webapp:
    image: chimera-webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:8.0-rc1-alpine
