services:
  cliapp:
    image: chimera-cliapp
    build:
      context: .
      dockerfile: Dockerfile.cliapp
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  webapp:
    image: chimera-webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:80"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:8.0-rc1-alpine
